name: See what we can install

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Packer
      run: |
        brew install packer
        # get version
        packer --version
    - name: Install Vagrant
      run: |
        brew cask install vagrant
        # get version
        vagrant --version
    - name: Install Virtualbox
      run: |
        brew install virtualbox
        # get version
        VBoxManage --version
    - name: See if we can spin up a box
      run: |
        vagrant up
        vagrant status
