name: See what we can install

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Packer
      run: |
        brew install packer
        # get version
        packer --version
    - name: Install Vagrant
      run: |
        brew install vagrant
        # get version
        vagrant --version
