name: See what we can install

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Packer
      run: |
        export VER="1.5.1"
        wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
        unzip packer_${VER}_linux_amd64.zip
        sudo mv packer /usr/local/bin
        # ensure we can run packer
        packer --version
